name: my_test_env
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cpuonly=2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.10.0
  - gmpy2=2.1.2
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.2
  - ipython=8.21.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pandas=2.1.4
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305  # Optional: Can be removed for Linux.
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchvision=0.15.2
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - vc=14.2  # Optional: Can be removed for Linux.
  - vs2015_runtime=14.27.29016  # Optional: Can be removed for Linux.
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - attrs==23.2.0
      - bayesian-optimization==1.4.3
      - chex==0.1.86
      - click==8.1.7
      - colorlog==6.8.2
      - diffrax==0.5.0
      - equinox==0.11.3
      - frozenlist==1.4.1
      - greenlet==3.0.3
      - icecream==2.1.3
      - ipywidgets==8.1.2
      - jax==0.4.25
      - jaxlib==0.4.25
      - jaxtyping==0.2.28
      - joblib==1.3.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.10
      - lightning-utilities==0.10.1
      - lineax==0.0.4
      - mako==1.3.3
      - matlabengine==23.2.1
      - ml-dtypes==0.3.2
      - msgpack==1.0.8
      - multidict==6.0.5
      - opt-einsum==3.3.0
      - optax==0.2.1
      - optimistix==0.0.6
      - optuna==3.6.1
      - pastel==0.2.1
      - poethepoet==0.10.0
      - protobuf==5.26.1
      - pyarrow==16.0.0
      - pydoe==0.3.8
      - pytorch-lightning==2.2.0.post0
      - pytorch-tcn==1.1.0
      - pyyaml==6.0.1
      - ray==2.20.0
      - referencing==0.35.1
      - rpds-py==0.18.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - sqlalchemy==2.0.30
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.3.0
      - tomlkit==0.12.3
      - toolz==0.12.1
      - torchcde==0.2.5
      - torchdiffeq==0.2.3
      - torchdyn==1.0.6
      - torchmetrics==1.3.1
      - torchsde==0.2.6
      - tqdm==4.66.2
      - trampoline==0.1.2
      - typeguard==2.13.3
      - widgetsnbextension==4.0.10
      - yarl==1.9.4
